In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:

df = pd.read_csv('student/student-mat.csv', sep=';')
df.head()

school sex  age address famsize Pstatus  Medu  Fedu     Mjob      Fjob  ...  \
0     GP   F   18       U     GT3       A     4     4  at_home   teacher  ...   
1     GP   F   17       U     GT3       T     1     1  at_home     other  ...   
2     GP   F   15       U     LE3       T     1     1  at_home     other  ...   
3     GP   F   15       U     GT3       T     4     2   health  services  ...   
4     GP   F   16       U     GT3       T     3     3    other     other  ...   

  famrel freetime  goout  Dalc  Walc health absences  G1  G2  G3  
0      4        3      4     1     1      3        6   5   6   6  
1      5        3      3     1     1      3        4   5   5   6  
2      4        3      2     2     3      3       10   7   8  10  
3      3        2      2     1     1      5        2  15  14  15  
4      4        3      2     1     2      5        4   6  10  10  

[5 rows x 33 columns]

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 395 entries, 0 to 394
Data columns (total 33 columns):
 #   Column      Non-Null Count  Dtype 
---  ------      --------------  ----- 
 0   school      395 non-null    object
 1   sex         395 non-null    object
 2   age         395 non-null    int64 
 3   address     395 non-null    object
 4   famsize     395 non-null    object
 5   Pstatus     395 non-null    object
 6   Medu        395 non-null    int64 
 7   Fedu        395 non-null    int64 
 8   Mjob        395 non-null    object
 9   Fjob        395 non-null    object
 10  reason      395 non-null    object
 11  guardian    395 non-null    object
 12  traveltime  395 non-null    int64 
 13  studytime   395 non-null    int64 
 14  failures    395 non-null    int64 
 15  schoolsup   395 non-null    object
 16  famsup      395 non-null    object
 17  paid        395 non-null    object
 18  activities  395 non-null    object
 19  nursery     395 non-null    object
 20  higher    

### No missing values

In [4]:
df.describe()

age        Medu        Fedu  traveltime   studytime    failures  \
count  395.000000  395.000000  395.000000  395.000000  395.000000  395.000000   
mean    16.696203    2.749367    2.521519    1.448101    2.035443    0.334177   
std      1.276043    1.094735    1.088201    0.697505    0.839240    0.743651   
min     15.000000    0.000000    0.000000    1.000000    1.000000    0.000000   
25%     16.000000    2.000000    2.000000    1.000000    1.000000    0.000000   
50%     17.000000    3.000000    2.000000    1.000000    2.000000    0.000000   
75%     18.000000    4.000000    3.000000    2.000000    2.000000    0.000000   
max     22.000000    4.000000    4.000000    4.000000    4.000000    3.000000   

           famrel    freetime       goout        Dalc        Walc      health  \
count  395.000000  395.000000  395.000000  395.000000  395.000000  395.000000   
mean     3.944304    3.235443    3.108861    1.481013    2.291139    3.554430   
std      0.896659    0.998862    1.113278    0.890741    1.287897    1.390303   
min      1.000000    1.000000    1.000000    1.000000    1.000000    1.000000   
25%      4.000000    3.000000    2.000000    1.000000    1.000000    3.000000   
50%      4.000000    3.000000    3.000000    1.000000    2.000000    4.000000   
75%      5.000000    4.000000    4.000000    2.000000    3.000000    5.000000   
max      5.000000    5.000000    5.000000    5.000000    5.000000    5.000000   

         absences          G1          G2          G3  
count  395.000000  395.000000  395.000000  395.000000  
mean     5.708861   10.908861   10.713924   10.415190  
std      8.003096    3.319195    3.761505    4.581443  
min      0.000000    3.000000    0.000000    0.000000  
25%      0.000000    8.000000    9.000000    8.000000  
50%      4.000000   11.000000   11.000000   11.000000  
75%      8.000000   13.000000   13.000000   14.000000  
max     75.000000   19.000000   19.000000   20.000000

### Going to look at the object columns
How many unique values in each column? We need to answer to see if we meed dummies

In [5]:
# df.dtypes == 'object' returns a series. Convert into array
mask = np.array(df.dtypes == 'object')
mask

array([ True,  True, False,  True,  True,  True, False, False,  True,
        True,  True,  True, False, False, False,  True,  True,  True,
        True,  True,  True,  True,  True, False, False, False, False,
       False, False, False, False, False, False])

In [6]:
# Using iloc, the df will filter out all the index locations
#Column numb where mask is false
obj_df = df.iloc[:, mask]

In [7]:
for col in obj_df.columns:
    print(obj_df[col].value_counts())

GP    349
MS     46
Name: school, dtype: int64
F    208
M    187
Name: sex, dtype: int64
U    307
R     88
Name: address, dtype: int64
GT3    281
LE3    114
Name: famsize, dtype: int64
T    354
A     41
Name: Pstatus, dtype: int64
other       141
services    103
at_home      59
teacher      58
health       34
Name: Mjob, dtype: int64
other       217
services    111
teacher      29
at_home      20
health       18
Name: Fjob, dtype: int64
course        145
home          109
reputation    105
other          36
Name: reason, dtype: int64
mother    273
father     90
other      32
Name: guardian, dtype: int64
no     344
yes     51
Name: schoolsup, dtype: int64
yes    242
no     153
Name: famsup, dtype: int64
no     214
yes    181
Name: paid, dtype: int64
yes    201
no     194
Name: activities, dtype: int64
yes    314
no      81
Name: nursery, dtype: int64
yes    375
no      20
Name: higher, dtype: int64
yes    329
no      66
Name: internet, dtype: int64
no     263
yes    132
Name: romantic, 

In [8]:
# Similar info as above
df.nunique()

school         2
sex            2
age            8
address        2
famsize        2
Pstatus        2
Medu           5
Fedu           5
Mjob           5
Fjob           5
reason         4
guardian       3
traveltime     4
studytime      4
failures       4
schoolsup      2
famsup         2
paid           2
activities     2
nursery        2
higher         2
internet       2
romantic       2
famrel         5
freetime       5
goout          5
Dalc           5
Walc           5
health         5
absences      34
G1            17
G2            17
G3            18
dtype: int64

In [9]:
dummy_df = pd.get_dummies(obj_df, dummy_na=False, drop_first=True)

In [10]:
df=pd.concat([df, dummy_df], axis=1)

In [11]:
df.drop(columns=obj_df.columns, inplace=True)

In [12]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 395 entries, 0 to 394
Data columns (total 42 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   age                395 non-null    int64
 1   Medu               395 non-null    int64
 2   Fedu               395 non-null    int64
 3   traveltime         395 non-null    int64
 4   studytime          395 non-null    int64
 5   failures           395 non-null    int64
 6   famrel             395 non-null    int64
 7   freetime           395 non-null    int64
 8   goout              395 non-null    int64
 9   Dalc               395 non-null    int64
 10  Walc               395 non-null    int64
 11  health             395 non-null    int64
 12  absences           395 non-null    int64
 13  G1                 395 non-null    int64
 14  G2                 395 non-null    int64
 15  G3                 395 non-null    int64
 16  school_MS          395 non-null    uint8
 17  sex_M           

In [13]:
from sklearn.model_selection import train_test_split

train_validate, test = train_test_split(df, test_size =.2,
                                        random_state=123)
train, validate = train_test_split(train_validate,
                                  test_size =.3, random_state=123)

In [14]:
# G3 is the final grade, we want to drop it for are X and predict on y
# Cap X since working with multiple variables
X_train = train.drop(columns=['G3'])
X_validate = validate.drop(columns=['G3'])
X_test = test.drop(columns=['G3'])

y_train = train[['G3']]
y_validate = validate[['G3']]
y_test = test[['G3']]


In [15]:
from sklearn.preprocessing import MinMaxScaler

In [16]:
scaler = MinMaxScaler(copy=True).fit(X_train)

X_train_scaled = scaler.transform(X_train)
X_validate_scaled = scaler.transform(X_validate)
X_test_scaled = scaler.transform(X_test)

In [17]:
# Is an array that needs to be a DF
X_train_scaled

array([[0.        , 1.        , 1.        , ..., 1.        , 1.        ,
        0.        ],
       [0.33333333, 0.75      , 0.75      , ..., 1.        , 1.        ,
        0.        ],
       [0.16666667, 0.5       , 0.5       , ..., 1.        , 1.        ,
        0.        ],
       ...,
       [0.        , 0.75      , 1.        , ..., 1.        , 1.        ,
        0.        ],
       [0.16666667, 1.        , 1.        , ..., 1.        , 1.        ,
        0.        ],
       [0.16666667, 0.5       , 0.5       , ..., 0.        , 1.        ,
        0.        ]])

In [18]:
X_train_scaled = pd.DataFrame(X_train_scaled, 
             columns=X_train.columns.values).\
            set_index([X_train.index.values])

X_validate_scaled = pd.DataFrame(X_validate_scaled, 
             columns=X_validate.columns.values).\
            set_index([X_validate.index.values])

X_test_scaled = pd.DataFrame(X_test_scaled, 
             columns=X_test.columns.values).\
            set_index([X_test.index.values])



In [19]:
from sklearn.feature_selection import SelectKBest, f_regression

In [20]:
# Select KBest is filter method

Initialize the f_selector object, defining the scoring method

In [21]:
f_selector = SelectKBest(f_regression, k=13)

Fit the object to our X and y

In [22]:
f_selector = f_selector.fit(X_train_scaled, y_train)

/usr/local/anaconda3/lib/python3.7/site-packages/sklearn/utils/validation.py:760: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


Transform DS to reduce to the K-Best features

In [23]:
X_train_reduced = f_selector.transform(X_train_scaled)

print(X_train.shape)
print(X_train_reduced.shape)

(221, 41)
(221, 13)


In [24]:
# Need to turn the array into df
X_train_reduced

array([[0.        , 1.        , 1.        , ..., 0.        , 0.        ,
        1.        ],
       [0.33333333, 0.75      , 0.75      , ..., 1.        , 0.        ,
        1.        ],
       [0.16666667, 0.5       , 0.5       , ..., 1.        , 0.        ,
        1.        ],
       ...,
       [0.        , 0.75      , 1.        , ..., 0.        , 0.        ,
        1.        ],
       [0.16666667, 1.        , 1.        , ..., 0.        , 0.        ,
        1.        ],
       [0.16666667, 0.5       , 0.5       , ..., 0.        , 0.        ,
        0.        ]])

In [27]:
f_support = f_selector.get_support()
print(f_support)

[ True  True  True  True  True  True False False False False False False
 False  True  True False  True False False False False  True False False
 False False False False False False  True False  True False False False
 False False  True False False]


In [28]:
X_reduced_scaled = X_train_scaled.iloc[:, f_support]

In [29]:
# :, everything iloc is saying ill give you index values to filter
# filter wjere the mask is fales, : before the comma is the rows
# 
f_feature = X_train_scaled.iloc[:,f_support].columns.tolist()
f_feature

['age',
 'Medu',
 'Fedu',
 'traveltime',
 'studytime',
 'failures',
 'G1',
 'G2',
 'sex_M',
 'Mjob_other',
 'reason_reputation',
 'guardian_other',
 'higher_yes']

In [30]:
from sklearn.feature_selection import RFE
from sklearn.linear_model import LinearRegression

In [31]:
# Initialize the linear regression object
lm = LinearRegression()

Init the RFE object, setting the hyperparameters to be in our linear model above lm and the # of features we want returned

In [36]:
rfe = RFE(lm,13)

In [37]:
X_rfe = rfe.fit_transform(X_train_scaled, y_train)

/usr/local/anaconda3/lib/python3.7/site-packages/sklearn/utils/validation.py:760: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


In [38]:
X_rfe

array([[0.        , 0.        , 0.        , ..., 0.        , 1.        ,
        1.        ],
       [0.33333333, 0.        , 0.        , ..., 0.        , 0.        ,
        1.        ],
       [0.16666667, 0.33333333, 0.33333333, ..., 0.        , 0.        ,
        1.        ],
       ...,
       [0.        , 0.        , 0.        , ..., 1.        , 1.        ,
        1.        ],
       [0.16666667, 0.        , 0.        , ..., 0.        , 0.        ,
        1.        ],
       [0.16666667, 0.        , 0.        , ..., 0.        , 0.        ,
        1.        ]])

In [41]:
mask = rfe.support_
mask

array([ True, False, False,  True, False,  True,  True, False, False,
       False, False, False,  True,  True,  True, False, False, False,
       False, False,  True,  True,  True, False, False, False, False,
       False, False, False, False, False, False,  True,  True, False,
       False, False, False,  True, False])

In [44]:
X_reduced_scaled_rfe = X_train_scaled.iloc[:,mask]
X_reduced_scaled_rfe

age  traveltime  failures  famrel  absences        G1        G2  \
142  0.000000    0.000000  0.000000    0.75  0.035714  0.357143  0.578947   
326  0.333333    0.000000  0.000000    0.75  0.053571  0.714286  0.789474   
88   0.166667    0.333333  0.333333    0.75  0.214286  0.500000  0.526316   
118  0.333333    0.666667  0.333333    1.00  0.357143  0.357143  0.368421   
312  0.666667    0.000000  0.333333    0.75  0.053571  0.642857  0.578947   
..        ...         ...       ...     ...       ...       ...       ...   
229  0.333333    0.333333  0.000000    0.50  0.178571  0.571429  0.526316   
61   0.166667    1.000000  0.000000    1.00  0.107143  0.428571  0.421053   
38   0.000000    0.000000  0.000000    0.75  0.035714  0.571429  0.631579   
243  0.166667    0.000000  0.000000    1.00  0.000000  0.642857  0.631579   
166  0.166667    0.000000  0.000000    0.75  0.071429  0.428571  0.526316   

     Mjob_health  Mjob_other  Mjob_services  schoolsup_yes  famsup_yes  \
142          0.0         0.0            0.0            0.0         1.0   
326          0.0         1.0            0.0            0.0         0.0   
88           0.0         0.0            1.0            0.0         0.0   
118          0.0         1.0            0.0            0.0         1.0   
312          0.0         1.0            0.0            0.0         0.0   
..           ...         ...            ...            ...         ...   
229          0.0         1.0            0.0            0.0         0.0   
61           0.0         0.0            1.0            1.0         1.0   
38           0.0         0.0            1.0            1.0         1.0   
243          0.0         0.0            1.0            0.0         0.0   
166          0.0         1.0            0.0            0.0         0.0   

     internet_yes  
142           1.0  
326           1.0  
88            1.0  
118           1.0  
312           1.0  
..            ...  
229           1.0  
61            1.0  
38            1.0  
243           1.0  
166           1.0  

[221 rows x 13 columns]

In [45]:
# features selected using rfe
X_reduced_scaled_rfe.columns.tolist()

['age',
 'traveltime',
 'failures',
 'famrel',
 'absences',
 'G1',
 'G2',
 'Mjob_health',
 'Mjob_other',
 'Mjob_services',
 'schoolsup_yes',
 'famsup_yes',
 'internet_yes']

In [46]:
!git status

On branch master
Your branch is up to date with 'origin/master'.

Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git restore <file>..." to discard changes in working directory)
	modified:   explore_telco.ipynb

Untracked files:
  (use "git add <file>..." to include in what will be committed)
	feature_engineering_walkthru.ipynb
	student/

no changes added to commit (use "git add" and/or "git commit -a")


In [47]:
!git add feature_engineering_walkthru.ipynb
!git commit -m "adding maggies walkthru on feature engineering"

[master bc4e3c9] adding maggies walkthru on feature engineering
 1 file changed, 1564 insertions(+)
 create mode 100644 feature_engineering_walkthru.ipynb


In [48]:
!git push

Enumerating objects: 4, done.
Counting objects: 100% (4/4), done.
Delta compression using up to 8 threads
Compressing objects: 100% (3/3), done.
Writing objects: 100% (3/3), 6.92 KiB | 6.92 MiB/s, done.
Total 3 (delta 1), reused 0 (delta 0)
remote: Resolving deltas: 100% (1/1), completed with 1 local object.
To https://github.com/george887/regression-exercises.git
   33cbdd7..bc4e3c9  master -> master
